# Generated by Django 5.1.2 on 2024-11-06 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='proffesion',
            new_name='profession',
        ),
    ]
