# Generated by Django 5.1.2 on 2024-11-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_proffesion_userprofile_profession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addmoneyinfo',
            old_name='add_money',
            new_name='expense_type',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='expenses',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='income',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='savings',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
