# Generated by Django 5.1.2 on 2024-11-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_addmoneyinfo_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmoneyinfo',
            name='expense_type',
            field=models.CharField(choices=[('Expense', 'Expense'), ('Income', 'Income'), ('Saving', 'Saving')], max_length=20),
        ),
    ]
