# Generated by Django 5.1.2 on 2024-11-19 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_addmoneyinfo_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addmoneyinfo',
            old_name='expense_type',
            new_name='money_type',
        ),
    ]
