# Generated by Django 5.1.2 on 2025-01-07 10:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_expense_type_addmoneyinfo_money_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
