# Generated by Django 5.1.2 on 2025-01-07 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_userprofile_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='expenses',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='income',
        ),
    ]
